import BaseProvider from "@/modules/core/providers/base-provider"
import "@mantine/core/styles.css"
import "@mantine/dates/styles.css"
import "mantine-datatable/styles.css"
import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import "react-toastify/ReactToastify.css"
import "./globals.css"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.className} antialiased`}>
        <BaseProvider>
          <div className='min-h-screen bg-gray-50 text-gray-900'>
            <NuqsAdapter>{children}</NuqsAdapter>
          </div>
        </BaseProvider>
      </body>
    </html>
  )
}
